- name: Demo on loops
  hosts: localhost
  tasks:
    - name: loop Example
      debug:
        msg: Fruit = {{item}}
      loop:
        - apple
        - banana
    - name: loop Exaple with Maps
      debug:
        msg: Fruit = {{item.name}}, Quantity = {{item.quantity}}
      loop:
        - {name: apple, quantity: 10}
        - {name: banana, quantity: 30}