- name: Demo on loops
  hosts: localhost
  tasks:
    - name: loop Example
      debug:
        msg: Fruit = {{item}}
      loop:
        - apple
        - banana
    - name: loop Exaple with Map
      debug:
        msg: Fruit = {{item}}
      loop:
        - apple
        - banana